apiVersion: v1
kind: Namespace
metadata:
  name: speedtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: speedtest
  namespace: speedtest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      tolerations:
      - key: "disk"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: lucio
      containers:
      - name: speedtest
        image: npflan/speedtest:v0.0.6
        resources:
          limits:
            memory: 256M
        livenessProbe:
          httpGet:
            path: /empty
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /empty
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 3
        ports:
          - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: speedtest
  namespace: speedtest
spec:
  type: NodePort
  clusterIP: 10.96.13.37
  externalTrafficPolicy: Local
  selector:
    app: speedtest
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
